[mypy]
python_version = 3.10
files = main.py,src
show_error_codes = True
pretty = True
warn_unused_configs = True
no_implicit_optional = True
check_untyped_defs = True

[mypy-PySide6.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-psutil.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True
